### ISSUE TITLE
Feature Request: keep track of movement across periodic boundary conditions

### ISSUE THREAD

**Issue by cpgoodri** [google/jax-md#10]
When analyzing a trajectory, it is sometimes necessary to "unwrap" motion across periodic boundaries (e.g. when calculating the diffusion constant of a particle). While this can sometimes be inferred from adjacent frames in a trajectory, this is not very robust and can lead to errors in some situations. I don't know what the best approach here is... LAMMPS has an integer variable (e.g. n1x, n1y, n1z, n2x, etc) that can be used to unwrap the positions, but there might be better ways.

**Comment by sschoenholz** [comment]
Thinking about this a little bit, for space.periodic (as opposed to space.periodic_general), I'm fairly sure it suffices to use a trivial shift function in whatever dynamics you choose. For example, the following code will perform a minimization with unwrapped coordinates. 

```python
displcement, _ = space.periodic(box_size)
_, shift = space.free()
energy_fn = energy.soft_sphere_pairwise(displacement, species=species, sigma=sigma)
unwrapped_init, unwrapped_apply = minimize.fire_descent(energy_fn, shift)
unwrapped_apply = jit(unwrapped_apply)
unwrapped_state = unwrapped_init(R)
```

Does this seem like a reasonable way to do this for you? If so, for space.periodic_general I think there's a trivial simple change that will allow you to choose whether you want your coordinates wrapped or unwrapped.

**Comment by cpgoodri** [comment]
This seems totally reasonable to me. Perhaps it could be a bit streamlined? Something like 
`displacement, shift = space.periodic(box_size, unwrapped = True)`

The one concern I might have (and this is really nit picking) is that you technically lose some precision if a particle crosses the same boundary too many times. I guess it depends on how "break proof" you want this to be.

**Comment by sschoenholz** [comment]
This is actually the solution that I had in mind (which is necessary for the periodic_general case, since using the trivial shift won't remap particle coordinates back into the unit cube).

I agree that there will be precision loss as the simulation goes on (if you were running with float32 positions). In principal, we could implement a "high-precision modulus" that casts to float64, performs the mod, and then casts back to float32. However, this will probably incur a pretty significant speed hit compared to the float32 version.

Another option would be to keep everything as-is and then have an argument like, `displacement, shift, unwrapper = space.periodic(box_size, unwrapping_function=True)` and then you could compute `R_unwrapped = unwrapper(R_old, R_new)`. The downside of this approach would be that it would fail if too much time had passed between unwrappings (aka it would count instances where R_new - R_old was larger than a half-lattice constant).

A final option that would be a bit more heavyweight would be to use a different encoding for positions in the case where you wanted unwrapped positions. In this case R would be a tuple of two arrays one which held the position within the box and one which held the lattice vector shift that would unwrap the positions so that `L, r = R` and then the wrapped positions would be `r` and the unwrapped positions would be `L + r`. 

I guess overall I would say I'm in favor of either the lossy first option or the third. I'll think about / play around with option 3 a bit and then update the thread. If you have a preference, let me know!

**Comment by cpgoodri** [comment]
I'm not sure I have a preference, since I don't think the precision issue will ever affect me personally. The third option seems ideal, but I don't know if its necessary. Perhaps we should ask around to get more input?
