### ISSUE TITLE
Vectorizing neighbor function: 'vmap(neighbor_fn)' doesn't work.

### ISSUE THREAD

**Issue by kdkyum** [google/jax-md#101]
```python
import jax.numpy as np
from jax import vmap
from jax_md.util import f32
from jax_md import space, energy

batch_size = 32
N = 100
dim = 2
box_size = 10

displacement, shift = space.periodic(box_size)
neighbor_fn, energy_fn = energy.soft_sphere_neighbor_list(displacement, box_size)
R = np.zeros((batch_size, N, dim), dtype=f32)

nbrs = vmap(neighbor_fn)(R)
```

When I tried to do vectorize the `neighbor_fn`, I got the following error:

```
~/.anaconda3/envs/md/python3.7/site-packages/jax_md/partition.py in _estimate_cell_capacity(R, box_size, cell_size, buffer_size_multiplier)
    173   cell_capacity = onp.max(count_cell_filling(R, box_size, cell_size))
--> 174   return int(cell_capacity * buffer_size_multiplier)
    175 

FilteredStackTrace: jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.
```

is there any solution to bypass this problem?

**Comment by sschoenholz** [comment]
Great question! At the moment, the neighbor list is designed to work with XLA's requirement that the shapes of all the arrays be known at compile time. As such, we need to allocate memory upfront for the maximum number of neighbors a particle can have. Simultaneously, we would like to use the state of the system to infer how much space we should allocate. As such, we use the pattern where `nbrs = neighbor_fn(R)` cannot be transformed by JAX since it uses the values of `R` to determine the size of the neighbor list to be allocated. 

For compatibility with JAX transformations, the `neighbor_fn` can also be called as `nbrs = neighbor_fn(R, nbrs)`. This is interpreted by our code as updating the neighbor list without changing is size. With this signature, the neighbor list function is compatible with JAX transformations. So, for example, one way that we could adapt your example to work would be using something like this,

```python
import jax.numpy as np
from jax import vmap
from jax_md.util import f32
from jax_md import space, energy

batch_size = 32
N = 100
dim = 2
box_size = 10

displacement, shift = space.periodic(box_size)
neighbor_fn, energy_fn = energy.soft_sphere_neighbor_list(displacement, box_size)
R = np.zeros((batch_size, N, dim), dtype=f32)

# Construct a neighbor list for the first state.
nbrs = neighbor_fn(R[0])

# Now we can use it inside JIT / vmap / etc...
# Note that here we only vectorize over positions, but you could vectorize over
# the initial state of the neighbor list as well.
all_nbrs = vmap(neighbor_fn, (0, None))(R, nbrs)
```

One caveat here is that, as I mentioned above, when called as `nbrs = neighbor_fn(R, nbrs)`, the neighbor function assumes that all of the neighbors can fit in the space allocated. If this assumption has been violated then `nbrs.did_buffer_overflow` will be set to True and you should try to allocate more space upfront (for example by setting `nbrs = neighbor_fn(R, extra_capacity=5)`). Thus, in your case it's worth checking,

```
print(np.any(all_nbrs.did_buffer_overflow))
```

to make sure that none of the neighbor lists overflowed. 

Hope this helps! Feel free to let me know if you have any other questions.

**Comment by kdkyum** [comment]
Thanks for the answer! It helped me a lot.
