### ISSUE TITLE
high_precision_sum is not high precision

### ISSUE THREAD

**Issue by gecrooks** [google/jax-md#132]
I don't think the high_precision_sum in jax_md.util works as intended.

https://github.com/google/jax-md/blob/6c60d5b589addeae62cf1002aa714293cf5f35a0/jax_md/util.py#L68

The problem is that jax does not enable float64 by default, and instead truncates to float32. A minimal example is below. The high_precision_sum and regular sum give the same answer. If you enable float64 by uncommenting the first line, then the default data type becomes float64 and the sums are still the same.

```
# from jax.config import config; config.update("jax_enable_x64", True)

from jax_md.util import high_precision_sum
import jax.numpy as jnp
from jax import random

key = random.PRNGKey(0)
key, pos_key = random.split(key)

values = random.normal(pos_key, [10000])
values = jnp.stack([values, -values]).reshape(-1)

print("exact sum: 0.0")
print("regular sum", jnp.sum(values))
print("high_precision_sum", high_precision_sum(values))

```

**Comment by sschoenholz** [comment]
Thanks for raising this! 

We do mention the `config.update('jax_enable_x64', True)` issue [here](https://github.com/google/jax-md#64-bit-precision), but perhaps we should raise a warning inside `high_precision_sum` and be more precise about the ramifications of failing to enable x64 mode. I'm a little wary of setting the flag within JAX MD since it will lead to behavior that isn't particularly canonical. Eventually, I hope that JAX will get rid of the flag altogether. 

Just to make sure I understand correctly, are you on board with the behavior when x64 mode is turned on (aka that the default dtype for `values` becomes `float64` and the two sums return the same value)? At the moment, the only time `high_precision_sum` and `jnp.sum` differ is if the input array is `float32` (or `float16`, I guess) and `jax_enable_x64 = True`. However, we feel like this case is important to support because it can often lead to nontrivial improvements to the simulation speed and, as long as reductions are done at `float64`, it does not seem to adversely affect stability.
 
Please don't hesitate to clarify if I've missed something.

**Comment by gecrooks** [comment]
Ah ha. I did see the mention under Technical gotchas, but read that to mean that's how you set the precision of the velocities and positions to float64. But looking at https://github.com/google/jax-md/blob/master/notebooks/lj_benchmark.ipynb I can see how this is meant to be used. If you enable x64 mode, but explicitly set the position and velocity to float32, then `high_precision_sum` works as expected.  Otherwise `high_precision_sum` is the same as a `np.sum`.
