### ISSUE TITLE
Neighbor Update issue

### ISSUE THREAD

**Issue by aniquetahir** [google/jax-md#141]
Apparently neighbor list update is failing when there is no buffer overflow.

Here is a notebook with a demonstration of the issue:
https://colab.research.google.com/drive/1HMxUMViHjlxWfQETBZDbuKtvpEW8LosI?usp=sharing

**Comment by sschoenholz** [comment]
Hey there! Thanks for submitting this issue. I can't seem to access the colab notebook, do you think you could share permissions?

**Comment by aniquetahir** [comment]
Sorry about that. You should be able to access it now.

**Comment by sschoenholz** [comment]
Fixed in 0d7d9c262c38f392633ac0c7676c20326bda148c. 

A few observations. The issue here was that the neighbor list was being allocated with capacity larger than the number of particles in the system. I fixed this by capping the maximum capacity at the system size. Note, however, that when this is the case you're better off using the `_pair` version of the energy functions that don't explicitly instantiate the neighbor list.

One other observation looking at your code. Note that: `energy_fn_nbrs = partial(energy_fn, neighbor=nbrs)` will use the same neighbor list throughout the simulation. I'm assuming you did this just to demonstrate the error, but you probably wouldn't want to do this in practice.

Let me know if you have any followup questions!

**Comment by aniquetahir** [comment]
Thanks for the suggestions. The issue appears to be resolved. I have one question.
When using neighbor list, is the maximum radius for calculating things dr_threshold+r_cutoff or r_cutoff. I was under the impression that dr_threshold is the width of the 'rings' used for doing the calculations at each iteration until r_cutoff is reached  but I am not completely sure about it.
