### ISSUE TITLE
Can jax-md run on GPUs?

### ISSUE THREAD

**Issue by Roy-Kid** [google/jax-md#157]
I want to add an Ewald summation and test how fast it can perform(If it can be fast enough then I can port the code to our autodiff multipole forcefield). So  I want to ask how can I run a simulation on multiple cores and GPUs? 

Thanks!

**Comment by cpgoodri** [comment]
Yes, jaxmd is designed to be able to run on GPUs! It does this through JAX, so you have to have JAX installed with GPU support (see [here](https://github.com/google/jax/#installation)). When running JAXMD, if JAX has access to a GPU then any JIT-compiled function will be run on a GPU. You can also use the JAX function pmap to run on multiple GPUs.

**Comment by Roy-Kid** [comment]
> PU then any JIT-compiled function will be run on a GPU. You can also use the JAX function pmap to run on multiple GPUs.

Nice! Thanks for your kindly help!

**Comment by sschoenholz** [comment]
I just want to add a few things to this, even though the issue is closed (thanks for answering, Carl!). 

1) As Carl said, if you install JAX with GPU support then JAX MD will take advantage of it (with or without JIT actually). If you do use JIT then code will be run on GPU without touching Python so it can be a lot faster.

2) On CPU JAX / XLA will naturally try to use parallelism to speed up computation (i.e. it will use multiple threads). However, in practice it seems not to be nearly as successful as LAMMPS.

3) While you can use `pmap` to take advantage of multiple GPUs, we haven't written JAX MD to allow large systems to be sharded across multiple GPUs. So right now, `pmap` i mostly for running multiple copies of the system across the different devices. So far, no one has had a use case where they needed multi-GPU support, but it is also a feature that could very reasonably be supported. If you do need this use case, make an issue so we can keep track. I make no promises as for timing though.

4) I'm really excited about Ewald sums and particle mesh Ewald sums (and actually have an old draft of them floating around). If you do put together an implementation, consider submitting it to JAX MD as a PR!

**Comment by Roy-Kid** [comment]
YES, I will contribute the code if I can make it and pass the tests. I used to work with LAMMPS and modified it under its elegant framework. Now I'm moving from a user to a developer, and I think JAX-MD is a good starter for me. I believe we can make it as successful as lammps.

The reason I want to use multi-GPUs is we are developing an auto differentiate multipole moments forcefield to calculate molecule interaction. We have written one prototype but it really slow. The reason is we are not following the pattern of JAX, such as no vmap but lots of loops. I want to rewrite this under the JAX-MD framework and figure out how fast Jax can be. My mentor says that we need to simulate 4K H2O for 4e6 timestep at least. The energy is directly calculated and force is the differentiate of energy. 

I need to dig into the JAX-MD code and extend it. I do like JAX and your work, and once I get familiar with it I can contribute to it. Thanks again for your kindly explanation, and I will implement it on one GPU at first. 😉
