### ISSUE TITLE
Why here is not floor(x)+1 but floor(x)?

### ISSUE THREAD

**Issue by DechinPhy** [google/jax-md#174]
https://github.com/google/jax-md/blob/593cea2b12e5864f6c764711a7955481bb6d910e/jax_md/partition.py#L125

**Comment by sschoenholz** [comment]
Good question! The cell list guarantees that cells will be at least the `minimum_cell_size`. However, it also builds cells so that the cells evenly fit into the simulation box. Note that the fewer cells in the cell list, the larger they will be. Since `box_size / minimum_cell_size` would give exactly the right sized cells if they could divide the box evenly, `floor(box_size / minimum_cell_size)` is the most cells that divide the box evenly while being larger than `minimum_cell_size`.

Let me know if that makes sense!

**Comment by DechinPhy** [comment]
> Good question! The cell list guarantees that cells will be at least the `minimum_cell_size`. However, it also builds cells so that the cells evenly fit into the simulation box. Note that the fewer cells in the cell list, the larger they will be. Since `box_size / minimum_cell_size` would give exactly the right sized cells if they could divide the box evenly, `floor(box_size / minimum_cell_size)` is the most cells that divide the box evenly while being larger than `minimum_cell_size`.
> 
> Let me know if that makes sense!

Yes it makes sense. I was confused by `minimum_cell_size` and `cell_size` that in many cases the `cell_size` could be a fixed value. But after thinking about it, only the `minimum_cell_size` been fixed is enough for these cases. Thank you very much!
