### ISSUE TITLE
NPT demo doesn't get the right pressure

### ISSUE THREAD

**Issue by emilannevelink** [google/jax-md#183]
Hello, I am hoping to get started using jaxMD. To start I went through the demos, but found that I wasn't able to figure out how to get the NPT ensemble to equilibrate to the target pressure.

Here is the plot that I'm getting with the defaults (tau = 1000dt)
![image](https://user-images.githubusercontent.com/21206213/164089800-5916e237-9a3f-4c49-a0ce-22fb0e045620.png)

I am wondering if there is a unit problem as I can see that the pressure initially decreases and stabilizes but doesn't reach the right set-point. Then, when the pressure changes, it never stabilizes to a new value.

The stabilization could be accelerated by changing the npt defaults. If I decrease tau to 100dt the pressure seems to equilibrate faster, but still not to the set points.
![image](https://user-images.githubusercontent.com/21206213/164102570-8f74f0dc-45c1-416b-b811-c916c488ccda.png)

Decreasing tau even further to 10dt, I no longer have temperature stable and the invariant is no longer constant, either.
![image](https://user-images.githubusercontent.com/21206213/164099255-42c28963-2d45-4af4-9431-b687dda4720a.png)

Could you please help me understand what is going on?

**Comment by sschoenholz** [comment]
Yikes, thanks a lot for pointing this out! It turns out the NPT simulation code had some issues that hadn't been addressed when I made changes to the pressure calculation in an earlier version. I fixed those changes along with a few more small things. I think everything should be working now, but let me know if you come across anything else unexpected!
