### ISSUE TITLE
Non-rectangular box tensor as lower triangular matrix in cell list

### ISSUE THREAD

**Issue by S-Roecken** [google/jax-md#194]
Hi,
In space.periodic_general() we can pass in a box tensor for a non-rectangular box (by setting the disable_cell_list=True #191), but it states in the comments that it requires the box tensor to be an upper triangular matrix. Is this actually the case, or does a lower triangular matrix work as well?

**Comment by sschoenholz** [comment]
Hey! Good question. Really, the only thing that `box` does is matrix-multiply (and inverse-multiply) the positions to map them from / to the unit-cube (see [here](https://github.com/google/jax-md/blob/d809de1bd916c8b4a53419be85c77ed8d62c307e/jax_md/space.py#L126)). So there is nothing strictly enforcing upper triangular, you can use whatever you want and perhaps the docs should be amended. It's really there because we mostly use upper-triangular in our experiments for conventions sake.

**Comment by S-Roecken** [comment]
Great, thank you for the fast reply!
